### ISSUE TITLE
Would you please tell me when to release a new version.

### ISSUE THREAD

**Issue by mogamusa31** [oupson/Kapng-Android#10]
Hello.

Thank you for approving the #8 PR.
So, I'm looking forward to the release of a new version including the #8 PR.

If you have already decided when to release a new version, would you please tell me when to release a new version.

Thank you for your response.

**Comment by oupson** [comment]
Sorry, I don't have a release date for the moment. I want to stabilise ExperimentalApngEncoder before releasing another version.

**Comment by mogamusa31** [comment]
I've acknowledged it!

I have only one request.

Currently, the projects I'm joined in have to support API19. So, until the API19 compatible version is released in this repository, I would like to release and use the API19 compatible one in my forked repository. Are you sure about that?

I'm sorry for making a rude request...

Thank you for your response.

**Comment by oupson** [comment]
I'm preparing a beta-3 with api 19 support.

**Comment by oupson** [comment]
I have released [1.0.10-beta3](https://github.com/oupson/Kapng-Android/releases/tag/1.0.10-beta3) with api 19 support (It was only tested on an emulator, as I don't have a kitkat device)

**Comment by mogamusa31** [comment]
Thank you for releasing 1.0.10-beta3!
It was very helpful!
