### ISSUE TITLE
I want to release image and pngBytes in PngEncoder after outputting Apng.

### ISSUE THREAD

**Issue by mogamusa31** [oupson/Kapng-Android#7]
Hello

I am using Kapng-Android to output Apng with an Android application.
Thank you very much.

Regarding the main subject, I want to release image and pngBytes in PngEncoder after outputting Apng because these variable remains after outputting Apng As you can see in the image below. would you offer me how to release these variable? If there is no way, I want to add a function for release. Specifically, I'd like you to add the following functions. Maybe I would be happy if the function was prepared as a static function.
```
fun release() {
    image?.recycle()
    image = null
    pngBytes = null
}
```
https://github.com/oupson/Kapng-Android/blob/master/apng_library/src/main/java/oupson/apng/imageUtils/PngEncoder.kt#L43-L46

Thank you for your response.

<img width="1459" alt="スクリーンショット 2020-05-08 17 08 17" src="https://user-images.githubusercontent.com/41275137/81761171-38963f80-9504-11ea-9c31-ba5175a98bc7.png">

**Comment by oupson** [comment]
Your issue should be fixed now, with the 2 latest commits. Thanks for your report.
